### ISSUE TITLE
Support milliseconds

### ISSUE THREAD

**Issue by zach-m** [bytefish/PgBulkInsert#11]
Hi and thank you for thius project.
LocalDateTime gets rounded to the nearest second in `de.bytefish.pgbulkinsert.pgsql.utils.TimeStampUtils`. Are there any plans to support millisecond precision?

**Comment by bytefish** [comment]
I think I copied the Java Date to Postgres Date conversion from the Postgres JDBC TimestampUtils. Do you know any source, that explains how to store dates with millisecond resolution?

**Comment by bytefish** [comment]
Here is how Npgsql handles finer Timestamp resolutions. It might be worth to see how it is handled there:

* https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/TypeHandlers/DateTimeHandlers/TimeStampHandler.cs

**Comment by bytefish** [comment]
I have added Microsecond Resolution for Timestamps. The 1.4 Release will be synced to Maven in some hours I guess. Please reopen the ticket, if the fix doesn't work for you.
