### ISSUE TITLE
Improvement in PgBinaryWriter

### ISSUE THREAD

**Issue by kowalczm** [bytefish/PgBulkInsert#14]
Hi,
I'm reviewing this project and spoted that PgBinaryWriter's buffer is declared as `buffer = new DataOutputStream(new BufferedOutputStream(out));`. I think we can remove 'BufferedOutputStream' as passed stream is 'PGCopyOutputStream' which itself is buffered. It could increase performace.

**Comment by bytefish** [comment]
Could you make a Pull Request and check if all Unit Tests are working?

**Comment by bytefish** [comment]
I will look into it this weekend.

**Comment by kowalczm** [comment]
Hi,
I have created PR for this: #15 
After further analyse I recognized that using BufferedOutputStream would be more efficient instead of realying on write(int) method in PGCopyOutputStream where is checking of  bound and one element array is used and coping. So more efficient is use BufferedOutputStream with configurable buffer size which should be larger that buffer size in PGCopyOutputStream  so then direct write is done and no buffer coping

**Comment by bytefish** [comment]
Pull Request #16 has been integrated into Version 2.1, which has been released to Maven and should be available in some hours. Thanks for the detailed Pull Request, Benchmarks and overall improvements! 👍
