### ISSUE TITLE
Support for Postgresql composite types

### ISSUE THREAD

**Issue by gliwka** [bytefish/PgBulkInsert#17]
I've implemented Postgresql [composite types](https://www.postgresql.org/docs/current/static/rowtypes.html)  on top of PgBulkInsert.

Would you be open to a pull request?

**Comment by bytefish** [comment]
Sure! Sounds great. 😎

**Comment by bytefish** [comment]
@gliwka I have modified the API to support some use cases raised by users. Let me know, if you need any help with migrating the code. 👍
