### ISSUE TITLE
mapString doesn't exist?

### ISSUE THREAD

**Issue by mgsteinkamp** [bytefish/PgBulkInsert#22]
The readme uses mapString in the example code, but there only seems to be mapText or mapVarChar in AbstractMapping.

**Comment by bytefish** [comment]
I changed some methods with the last major release and I must have forgot to update the README. 😳 I will fix it, or you can make a Pull Request changing it from ``mapString`` to ``mapText``. 🙏

**Comment by bytefish** [comment]
README has been updated. 👍
