### ISSUE TITLE
ByteValueHandler incorrectly write byte?

### ISSUE THREAD

**Issue by kowalczm** [bytefish/PgBulkInsert#28]
https://github.com/bytefish/PgBulkInsert/blob/7105a1a0a837c15218428226427fe49e7605010f/PgBulkInsert/src/main/java/de/bytefish/pgbulkinsert/pgsql/handlers/ByteValueHandler.java#L13

 shouldn't be:
`buffer.writeByte(value.byteValue());`
?

**Comment by bytefish** [comment]
Is there currently an error, when writing a byte? We could change it to ``writeByte``, but I hope nothing breaks doing it. 😅

**Comment by kowalczm** [comment]
seems to be working but just spoted such discrepancy

**Comment by bytefish** [comment]
I will change it. If all unit tests pass, it should be safe to change. You can also make a Pull Request to change it. 👍
