### ISSUE TITLE
Ingesting stream of entities in parallel

### ISSUE THREAD

**Issue by bchapuis** [bytefish/PgBulkInsert#33]
First of all, thanks a lot for the great work! When saving entities, the `PgBulkInsert` and the `BulkProcessor` classes both have synchronized blocks. In particular, when saving a parallel stream with `PgBulkInsert`, the `saveEntitySynchronized` method seems to constitute a consumer bottleneck. Would it make any sense to have several threads/connection copying data into the database in parallel? If so, what would be the recommended way do that?

**Comment by bytefish** [comment]
I think I will soon release a 4.0 version and remove the ``BulkProcessor`` class and ``saveAll(PGConnection connection, Stream stream)`` completely. There is already a method ``saveAll(PGConnection connection, Collection<T> collection)`` which doesn't synchronize.

Yes, opening several connections and doing a Parallel COPY is the simplest way of parallelizing the insert. I looked around and the simplest way to create a Partitioned Stream (read: doing the batching) is probably with Guavas ``Iterators.partition`` method.

Writing this in GitHub, I think something like the following would be the easiest way to parallelize the Inserts of a Stream:

```java
@Test
public void bulkInsertDataTest() throws SQLException {

    // Create the Writer to use for Bulk Writes:
    PgBulkInsert<MyObject> writer = new PgBulkInsert<MyObject>(new MyObjectMapper());

    // Create a Fake Data Stream:
    Stream<MyObject> stream = IntStream
            .range(0, 100000)
            .mapToObj(i -> new MyObject(i));

    // Partition the Stream into 10000 Element Batches:
    UnmodifiableIterator<List<MyObject>> batches = Iterators.partition(stream.iterator(), 10000);

    // Create the Batch Spliterator, probably it can be improved?
    Spliterator<List<MyObject>> batchSpliterator = Spliterators.spliteratorUnknownSize(batches, Spliterator.ORDERED);

    // Build a Parallel Stream using the Spliterator:
    Stream<List<MyObject>> parallelBatchesStream = StreamSupport.stream(batchSpliterator, true);

    // Now use the Batching Iterator from Guava to insert in Parallel:
    parallelBatchesStream
            .forEach(batch -> {
                // Always open up a new Connection:
                try(Connection connection = DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/sampledb", "philipp", "test_pwd")) {
                    // Cast into the underlying PGConnection:
                    PGConnection pgConnection = PostgreSqlUtils.getPGConnection(connection);
                    // And save it to DB:
                    writer.saveAll(pgConnection, batch);
                } catch (Exception e) {
                    e.printStackTrace();
                };
            });
}
```

**Comment by bytefish** [comment]
@bchapuis I have added a sample for the above code. It shows how to do a Parallel COPY with PostgreSQL. The reason I want to delete the ``saveAll(PGConnection connection, Stream stream)`` is because a Parallel Stream doesn't give any benefit, when it comes to inserts. It's better to build Batches and do Parallel COPYs, each having its own connection so it is also done multithreaded on server.

**Comment by bchapuis** [comment]
@bytefish Thanks a lot for the example, I will give a try to Guava's `Iterators.partition` and come back to you with more insights.

**Comment by bytefish** [comment]
I saw problems with the Parallel Streams when printing the Thread ID. Apparently Java is not distributing the Batches to the several Threads when using Parallel Streams. I simplified the whole pipeline massively using an ``ExecutorService``:

```java
    @Test
    public void bulkInsertDataTest() throws SQLException {

        // Create the Writer to use for Bulk Writes:
        PgBulkInsert<MyObject> writer = new PgBulkInsert<MyObject>(new MyObjectMapper());

        // Create a Fake Data Stream:
        Stream<MyObject> stream = IntStream
                .range(0, 1000000)
                .mapToObj(i -> new MyObject(i));

        // Partition the Stream into 10000 Element Batches:
        UnmodifiableIterator<List<MyObject>> batches = Iterators.partition(stream.iterator(), 10000);

        ExecutorService executorService = Executors.newFixedThreadPool(4);

        batches.forEachRemaining((batch) -> {
            try {
                executorService.submit(() -> writeBatch(writer, batch)).get();
            } catch(Exception e) {
                e.printStackTrace();
            }
        });

        shutdownAndAwaitTermination(executorService);
    }

    public static void shutdownAndAwaitTermination(ExecutorService pool) {
        pool.shutdown(); // Disable new tasks from being submitted
        try {
            // Wait a while for existing tasks to terminate
            if (!pool.awaitTermination(60, TimeUnit.SECONDS)) {
                pool.shutdownNow(); // Cancel currently executing tasks
                // Wait a while for tasks to respond to being cancelled
                if (!pool.awaitTermination(60, TimeUnit.SECONDS))
                    System.err.println("Pool did not terminate");
            }
        } catch (InterruptedException ie) {
            // (Re-)Cancel if current thread also interrupted
            pool.shutdownNow();
            // Preserve interrupt status
            Thread.currentThread().interrupt();
        }
    }
```

I updated the Unit Test.

**Comment by bchapuis** [comment]
It definitely looks simpler and I will give it a try. However, in my understanding the `forEach` method of the `Stream` comes with some sort of back pressure, i.e., the stream won't be processed faster than the ability of the `Consumer` to ingest it. Here, the queue of the `ExecutorService` acts as an intermediary buffer, which might become problematic in the context of very large imports.

**Comment by bytefish** [comment]
Really? Streams in Java are Pull-based. I know, that RxJava Observables / Reactive Streams might end up in Backpressure when the Consumer is too slow... Does the same hold for normal Java 8 Streams?

**Comment by bchapuis** [comment]
I was guessing, so back-pressure is probably the wrong term here. However, the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html) states the following:

> Streams are lazy; computation on the source data is only performed when the terminal operation is initiated, and source elements are consumed only as needed.

In my understanding, the `Consumer` that submits the jobs could make progress faster than the `ExecutorService`.

**Comment by bytefish** [comment]
I think controlling the queue length with an approach similar to 5. would be useful to control backpressure: https://www.nurkiewicz.com/2014/11/executorservice-10-tips-and-tricks.html.

**Comment by bchapuis** [comment]
Thanks a lot! I ended up using a custom `Consumer` in conjunction with a `PoolingDataSource`.

```java
public class PgBulkConsumer<TEntity> implements Consumer<Collection<TEntity>> {

    private final PgBulkInsert<TEntity> bulkInsert;

    private final DataSource dataSource;

    public PgBulkConsumer(PgBulkInsert<TEntity> bulkInsert, PoolingDataSource dataSource) {
        this.bulkInsert = bulkInsert;
        this.dataSource = dataSource;
    }

    @Override
    public void accept(Collection<TEntity> entities) {
        try (Connection connection = dataSource.getConnection()) {
            PGConnection pgConnection = connection.unwrap(PGConnection.class);
            bulkInsert.saveAll(pgConnection, entities);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
```
The main difficulty is to efficiently partition the stream, which can be achieved with a custom `Spliterator`.

**Comment by bytefish** [comment]
Maybe you can make a Pull Request and add it to the existing Unit Test I have referenced in the ticket? Or you add your own unit test to the project and make a Pull Request? My test isn't a beauty, but it works. 🥇 

I am wondering: How do you control the ``ForkJoinPool`` queue size in your example?

**Comment by bytefish** [comment]
Please add it as a separate method, so my example isn't overriden. 😇 I would love to perform some experiments later to see if / how improves the throughtput for PostgreSQL. 😎

**Comment by bchapuis** [comment]
In my understanding the Stream is lazily evaluated, i.e., data is read by the Spliterator only when the Consumer asks for it. I don't know if there is an underlying queue, but the memory consumption seems to remain relatively stable. In my case, I consume a relatively large file (40GB), which is read and persisted progressively in postgres. To write the Spliterator the following article was particularly useful:
https://www.airpair.com/java/posts/parallel-processing-of-io-based-data-with-java-streams

**Comment by bytefish** [comment]
I see. Thanks for the input! I am not an expert when it comes to parallelism in Java. So it is also interesting for me to see how to implement it the best way.

**Comment by bytefish** [comment]
By the way, very clever to use a custom spliterator. 😎

**Comment by bchapuis** [comment]
I'm not an expert neither. Thanks for the great work on PgBulkInsert, the experience and the performances were very smooth so far :smile:

**Comment by bytefish** [comment]
Good to hear. 😌 Let me know, if you have any problems.

**Comment by bytefish** [comment]
@bchapuis Is it possible to share the spliterator? 😇

**Comment by bchapuis** [comment]
@bytefish sure, with pleasure, let me just clean it and make it a bit more generic.

**Comment by bchapuis** [comment]
@bytefish I just create a repository containing a work in progress. In my first attempt, I tried to create a `Spliterator` for each partition. However, it seams that if the stream is lightweight (does not involve a lot of processing), batching several partitions together becomes necessary. I still have some doubts on what's happening here, but I really see great performance improvements as I increase the number of threads in the forkjoinpool (notice that I use a SSD drive).
https://github.com/bchapuis/stream-util

**Comment by bytefish** [comment]
Great job! I am currently also experimenting with importing large scale dataset in parallel with .NET:  https://github.com/bytefish/GermanWeatherDataExample. It's a little different in C#, but... I have the problem, that the database writes the data fast enough, but the CSV Reader / Mapping is too slow - no matter how much I optimized it. If I find a solution, that scales I will let you know.
