### ISSUE TITLE
 Could not obtain a PGConnection

### ISSUE THREAD

**Issue by dingliyy** [bytefish/PgBulkInsert#34]
SpringBoot项目使用jdbcTemplate获取的java.sql.Connection不行啊。

`Connection connection = jdbcTemplate.getDataSource().getConnection();
bulkInsert.saveAll(PostgreSqlUtils.getPGConnection(connection), duplicatRemovedEvidences.stream());
`
报错：de.bytefish.pgbulkinsert.exceptions.PgConnectionException: Could not obtain a PGConnection

怎么解决啊？

**Comment by dingliyy** [comment]
> SpringBoot项目使用jdbcTemplate获取的java.sql.Connection不行啊。
> 
> `Connection connection = jdbcTemplate.getDataSource().getConnection(); bulkInsert.saveAll(PostgreSqlUtils.getPGConnection(connection), duplicatRemovedEvidences.stream()); `
> 报错：de.bytefish.pgbulkinsert.exceptions.PgConnectionException: Could not obtain a PGConnection
> 
> 怎么解决啊？

知道了，用C3P0NativeJdbcExtractor转成PGColnnection

**Comment by dingliyy** [comment]
> SpringBoot项目使用jdbcTemplate获取的java.sql.Connection不行啊。
> 
> `Connection connection = jdbcTemplate.getDataSource().getConnection(); bulkInsert.saveAll(PostgreSqlUtils.getPGConnection(connection), duplicatRemovedEvidences.stream()); `
> 报错：de.bytefish.pgbulkinsert.exceptions.PgConnectionException: Could not obtain a PGConnection
> 
> 怎么解决啊？

知道了，用C3P0NativeJdbcExtractor转成PGColnnection

**Comment by bytefish** [comment]
你真是太聪明了！👍
