### ISSUE TITLE
Add support for TimestampTz PostgreSQL Type mapped to java.time.ZonedDateTime

### ISSUE THREAD

**Issue by jonfreedman** [bytefish/PgBulkInsert#39]
It would be useful to be able to bulk insert into a TIMESTAMPTZ column, according to https://www.postgresql.org/docs/current/datatype-datetime.html the storage of both TIMESTAMP and TIMESTAMPTZ is 8 bytes so all that's necessary is to covert to UTC.  If a database needs to maintain the inserted timezone it appears that must be dealt with separately.

**Comment by bytefish** [comment]
I have released it to the Central Maven Repository as 3.4. It should be available soon.

**Comment by jonfreedman** [comment]
Thanks, that's great

**Comment by juriad** [comment]
It would also be good to support OffsetDateTime and Instant too. All of these map to TIMESTAMPTZ.
