### ISSUE TITLE
Adding the postgres dB connection settings in sink

### ISSUE THREAD

**Issue by rajancherma** [bytefish/PgBulkInsert#41]
Have to set idle connection timeout and max eviction time in the postgres flink .can you please suggest where I have to set dB specific configuration in the flink code

**Comment by bytefish** [comment]
If you are using this library, then you can pass in the Timeout in the connection. About Flink: I am sorry, but I won't be able to help. It's been a long time since I wrote the Apache Flink examples and I don't have time to look at it in the upcoming weeks. Best luck with your projsct!
