### ISSUE TITLE
Can I use this without a Java model? Also, how does it scale?

### ISSUE THREAD

**Issue by skunkiferous** [bytefish/PgBulkInsert#46]
Hi.

I have a use-case, and I'm wondering if it would be well served by your library.

Our app-server is written in Java, and uses a proprietary NOSQL DB. We are refactoring our code to use PostgreSQL instead. I wrote an "Exporter" that export the NOSQL DB to MessagePack, and an "Importer" that reads those files, and generate "INSERTs" for each entity, on a different server.

This works fine for our test DB, but our productive DB is 140M entities / 300GB, and with my current prototype, it would take maybe a week to import! (our DBAs haven't looked into optimizing it yet) We don't plan a productive "Big Bang/One Shot" conversion, but even for a test-system, a copy time of a week is not practical.

So, my first question is: Could I use your library to first "export" to the PostgreSQL "COPY format", and then "import" those files "in bulk" on a different machine?

My second question is: Is there some limitation to your library that would cause problem at this scale? (140M rows, 300GB, DB Server has 64GB Ram)

My third question is: Does your library require a "Java Model" in the form of some "bean" class per table?

**Comment by bytefish** [comment]
Well. There are many ways to achieve what you plan and maybe you don't need a library like mine. Besides the Binary COPY Protocol, which the library implements, there is also a way to read data from STDIN:

* https://www.postgresql.org/docs/current/sql-copy.html

Maybe you could also transform the data to import to a CSV file and import it using the STDIN of Postgres. There is also a thing to keep in mind: You should fire up multiple COPY jobs at the same time so your server is saturated. Because each COPY only utilizes a single worker process.

**Comment by bytefish** [comment]
I am thinking a little about it.

You said you already wrote an Exporter, that writes INSERT statements. Maybe a simple way to increase performance without too many changes is to use multiline inserts, like in this Stackoverflow post:

* https://stackoverflow.com/a/32279203/513875

This should be more or less equivalent to a COPY from STDIN.

And it shouldn't require much changes on your side.

**Comment by skunkiferous** [comment]
Hi. With minimal changes, I could refactor to add only the indexes and constraints _after_ the import, and also use those "multiline inserts", but idk how much faster that be.

Instead, I could run the COPY command manually. My problem is, our data is not simply integers and strings, but we have many arrays, in particular byte arrays (serialized Java objects), and so I don't know how to use that data to produce correctly formatted files that COPY can read.

Also, we have some "floats/double" data, and they usually cannot be exported and re-imported "exactly" AFAIK, if they have to be turned into strings, when using a _text_ format for the transfer.

Your library looked like the right tool for the job. It's just that you use a "bean" in your example; I produce my data not from Java objects, but rather from the "low level" API that my database offers, which is somewhat similar to JDBC.

**Comment by bytefish** [comment]
What would an API for your usecase look like? I mean like, what would a perfect API look like to be easily integrated.

**Comment by skunkiferous** [comment]
MessagePack itself is not "table oriented", so I would imagine something more like a JDBC prepared statement.
You define a table, with a name, and a list of columns, with names and SQL types, and then you define your "inserts" by calling something like either putInt(name, ...) or putInt(position, ...) for each column. Either you create a new "row" object per row, that you fill, or call something like executeBatch() on a reusable object. And you just do the same for all tables.
Idk if COPY use one file per table, or one per DB; I guess both would work for me. But it might be easier to use "one file per table" when generating the file, because then it can easily be done in parallel with multiple threads.
One particular of our use-case, is that we use the PostgreSQL "table inheritance" (CREATE TABLE ... INHERITS ...).
Also, JDBC is well-known, so that makes another API that works the same way easier to use.

**Comment by bytefish** [comment]
Sounds good. It would be great if you could write some Java code on how you envision to use such an API. Like how should the rows be created, ... Just as an example, so I have a starting point on what classes are needed and such. 

At the moment I am 🤒, so I won't be able to work on it the days ahead.

**Comment by bytefish** [comment]
Here is my first attempt at designing the API. I called the class ``SimpleRowWriter``. Please take a look at the test and let me know, what you think:

* https://github.com/bytefish/PgBulkInsert/blob/master/PgBulkInsert/src/test/java/de/bytefish/pgbulkinsert/rows/SimpleRowWriterTest.java#L24

**Comment by skunkiferous** [comment]
I looked at your example; that would do your fine, I think (as long as the result is a "COPY file", and not an actual PG table).

**Comment by bytefish** [comment]
This is a Binary COPY to Postgres. There is no file being created, the data is written to Postgres using the Binary COPY Protocol using the Table and Rows specified in the ``SimpleRowWriter``.

**Comment by bytefish** [comment]
Although this is C#, it makes a good introduction: 

* https://www.npgsql.org/doc/copy.html#binary-copy

**Comment by skunkiferous** [comment]
I was looking at this problem from the point-of-view of my current
solution, which is to use temporary files to transport the data. I
guess that doubles the entire transfer time. But until recently we
were experimenting with the precise PostgreSQL mapping, so I had to
re-import the data multiple times, and it made sense to export it only
once.

OTOH, we mostly locked-down the PostgreSQL mapping now, so if a direct
transfer is easy to implement, I really should try it.

If we're discussing design, I have to assume it's not in your API yet,
and you need to code it. Would that be much work? I just wanted to
know if something like that was possible; I did not expect you to
rewrite/extend your API just for my use-case...

**Comment by bytefish** [comment]
I don't see a need for intermediate files. Now without knowing anything about your processing pipeline, but I guess you get the data serialized using MessagePack and then deserialize it. From there you could basically write an adapter, that writes to the Postgres tables.

**Comment by skunkiferous** [comment]
You are totally right! I thought I would produce a "COPY file" with the exporter, and use that file in the importer. But then I would have to modify both, and make the exporter "DB specific". If I just keep the MessagePack temporary files, but simply import the data into PostgreSQL using a different format, my pipeline is basically the same, and I have the least changes. I'm really glad I discussed this with you; I feel like I'm not at my "brightest" atm.  :D

**Comment by bytefish** [comment]
I am closing the issue. Feel free to answer or ask anyway.
