### ISSUE TITLE
Add support for tstzrange

### ISSUE THREAD

**Issue by csimplestring** [bytefish/PgBulkInsert#52]
Hi, thanks for this awesome library!

recently I have to use the tstzrange type in postgres. Is there plan to support this or any useful links/documentation about how to customise the IValueHandler?

I checked some implementation of the IValueHandler, for me, the missing part is where can I find the pg binary specification protocol to convert tstzrange to binary data.

Many thanks!

**Comment by bytefish** [comment]
So what I am basically doing in this library is to use the Binary Protocol, that can be found in Npgsql. The reason is simply because they already did the tedious task of Reverse Engineering it from Postgres. 

As for a Range the relevant protocol stuff can be found here: 

* https://github.com/npgsql/npgsql/blob/d4132d0d546594629bcef658bcb1418b4a8624cc/src/Npgsql/TypeHandlers/RangeHandler.cs

The idea is to map this to PgBulkInsert, you can see some similarities in how I structured the API. So if you feel like giving it a go, let me know if you need help with the ValueHandler stuff.

**Comment by bytefish** [comment]
I quickly looked through the code. I think there is no specific tstzrange  handler, but the generic ``NpgsqlRange<T>`` that is used to write ranges of any type.

As a starting point: How would you love to call a tstzrange API in PgBulkInsert? So to say, which Java Type would you map to Postgres from?

**Comment by csimplestring** [comment]
hey, thanks for quick response.

Since I am using the _com.vladmihalcea.hibernate.type.range.Range_ class (this library supports more types that Hibernate does not), so `Range<ZonedDateTime>` is the Java Type to map to Postgres 'tstzrange' in my case.

But I understand, ideally, this library should not depend on another third-party library's type. Probably this library can create its own Range type for easy use.

**Comment by bytefish** [comment]
Yes, that's what I am doing right now. 👍 Give me a moment to come up with an initial implementation and then we iterate on that.

**Comment by csimplestring** [comment]
many thanks!!!

**Comment by bytefish** [comment]
I have added an initial implementation, 

I will now need to add it to the API surface and add some Unit Tests.

**Comment by csimplestring** [comment]
Awesome. Looking forward to it, if you need any help from me, I am glad to help.

**Comment by bytefish** [comment]
There were quite some changes neccessary to implement this quickly, with some more brain power one might improve the implementation... but I think it is good enough for now. So.

Could you please take a look at the Unit Test here: 

https://github.com/bytefish/PgBulkInsert/blob/19befad4556652b005488a79db267b6ae597c8fa/PgBulkInsert/src/test/java/de/bytefish/pgbulkinsert/pgsql/handlers/RangeTypesTest.java#L68

And also take a look at the Range Data Model:

https://github.com/bytefish/PgBulkInsert/blob/19befad4556652b005488a79db267b6ae597c8fa/PgBulkInsert/src/main/java/de/bytefish/pgbulkinsert/pgsql/model/range/Range.java#L17

What do you think?

**Comment by csimplestring** [comment]
@bytefish  the unit tests already shows its usage, and the added method on SimpleRow is exactly what I need. They look really nice to me.

**Comment by bytefish** [comment]
Cool. Well honestly, I am a bit afraid to release it without testing for all Edge Cases like... Empty Ranges, Infinite, Inclusive Bounds, ... 

I would release an alpha version, so you can run some tests. But I have never worked with Pre-Releases in the Maven Central Repository. 🤭 So I first need to read up, if there is anything special when doing a Pre-Release.

**Comment by csimplestring** [comment]
Sure. The alpha version is pretty enough for me now. I can also run some test covering some edge cases in my project. If there were some issues, I will give feedback here.

**Comment by csimplestring** [comment]
@bytefish  Morning. One edge case is found: 
Input is **[2016-08-18 00:00:00.0Z,)**
But the following exception occurs:
```

Caused by: java.io.IOException: Write to copy failed.
	at org.postgresql.copy.PGCopyOutputStream.write(PGCopyOutputStream.java:86)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
	at java.io.DataOutputStream.writeInt(DataOutputStream.java:199)
	at de.bytefish.pgbulkinsert.pgsql.handlers.StringValueHandler.internalHandle(StringValueHandler.java:16)
	at de.bytefish.pgbulkinsert.pgsql.handlers.StringValueHandler.internalHandle(StringValueHandler.java:10)
	at de.bytefish.pgbulkinsert.pgsql.handlers.BaseValueHandler.handle(BaseValueHandler.java:19)
	... 108 more
Caused by: org.postgresql.util.PSQLException: ERROR: insufficient data left in message
  Where: COPY ondclassdetails_staging, line 1, column period_valid
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1116)
	at org.postgresql.core.v3.QueryExecutorImpl.writeToCopy(QueryExecutorImpl.java:998)
	at org.postgresql.core.v3.CopyInImpl.writeToCopy(CopyInImpl.java:37)
	at org.postgresql.copy.PGCopyOutputStream.writeToCopy(PGCopyOutputStream.java:133)
	at org.postgresql.copy.PGCopyOutputStream.write(PGCopyOutputStream.java:84)
	... 114 more
```

**Comment by bytefish** [comment]
I will add a test case and see if I can fix it. 😀

**Comment by bytefish** [comment]
Your analysis seems to be correct. I see how to rewrite it, so it fits the use case.

**Comment by csimplestring** [comment]
Morning. I think I found the root cause at line 27 - 33 in RangeValueHandler:
```
        if(!value.isUpperBoundInfinite()) { 
            valueHandler.handle(buffer, value.getLowerBound());
        }

        if(!value.isUpperBoundInfinite()) {
            valueHandler.handle(buffer, value.getUpperBound());
        }
```
should change to
```
        if (!value.isLowerBoundInfinite) {
            valueHandler.handle(buffer, value.lowerBound)
        }

        if (!value.isUpperBoundInfinite) {
            valueHandler.handle(buffer, value.upperBound)
        }
```

**Comment by bytefish** [comment]
Yes, I also recognized this. But it has to do with the Byte-Arithmetics. It goes off somewhere, I am always in deep fear doing this in Java due so the signature in bytes. 👍 If I hardcode the flags like this, the test works... But I need to find out, where in the Bit Operations I am wrong.

```java
    @Override
    protected void internalHandle(DataOutputStream buffer, Range<TElementType> value) throws Exception {
        buffer.writeInt(getLength(value));
        buffer.writeByte(8);

        if (value.isEmpty()) {
            return;
        }

        if(!value.isLowerBoundInfinite() && value.getLowerBound() != null) {
            valueHandler.handle(buffer, value.getLowerBound());
        }

        if(!value.isUpperBoundInfinite() && value.getUpperBound() != null) {
            valueHandler.handle(buffer, value.getUpperBound());
        }
    }
```

**Comment by bytefish** [comment]
Yes. First of all you are right with the wrong lower bound in my code. Fixed then. Next I think the value in my unit test was wrong and looked like this "[DATE,]" instead of "[DATE,)". BUT maybe it should work with "[DATE,]" also and not lead to a crash. What do you think?

**Comment by csimplestring** [comment]
I have the same confusion with the 'infinite': if the upperBound is already infinite, does 'inclusive' matter or not? But it is about the how Postgres represents the string of range and it depends on how developers write it. Therefore the test looks correct to me.

**Comment by bytefish** [comment]
OK. After running some tests with Npgsql I came to the following conclusion: What should happen if the value passed to the Lower Bound or Upper Bound in the ``Range`` is null? If I set a "null" value as upper bound and have the upper bound defined as Inclusive (which is done by default)... then the Binary Copy fails. If I set the bound to Infinite, when a value is null... everything works as expected.

That means to me... If someone uses the constructor like this ``Range(dateTime1, null)`` it should be made clear from comments, that this maps to Postgres ``[dateTime1,)". And I don't want this to be configurable, cause this would only cause errors. 

I will add some more tests and then make a new release.

**Comment by bytefish** [comment]
I have released ``4.0-alpha-2`` to the Central Maven Repositories. Give it a try! 👍

**Comment by csimplestring** [comment]
👍 will try!

**Comment by csimplestring** [comment]
Running tests in my project and it works perfectly! And it is really fast.

Another question is: do I need to manually close the PgConnection passed to `pgwriter.open(connection)`? 

Since I am using HikariDataSource, I have to get the PgConnection like `dataSource.connection.unwrap(PGConnection::class.java)`,  just want to make sure if it might cause connection leak.

**Comment by bytefish** [comment]
I don't think I am closing the connection explicitly. So it would be best to close it after using it.

**Comment by bytefish** [comment]
@csimplestring If you didn't hit any errors, I will add some more range types and tests. And then I will do an official 4.0 release.

**Comment by csimplestring** [comment]
@bytefish  Everything is ok! Wait for the official release!

**Comment by bytefish** [comment]
@csimplestring I have uploaded the 4.0 to Maven Central Repository. It may time until it is synced and indexed by their servers. I am closing this ticket, but if you hit any problems, feel free to reopen or comment on this ticket.
