### ISSUE TITLE
map double in JpaMapping

### ISSUE THREAD

**Issue by t0bst4r** [bytefish/PgBulkInsert#57]
Hello,

you've just implemented the JpaMapping with my colleague @cheffe in #54  😄 
Now I've some problems writing doubles into the database.

I expected PGBulkInsert to do the mapping as follows:

Java / Kotlin Type: Double
Postgre Type: Double Precision

But the following lines are mapping the java double type to single precision because you are using the function mapFloat instead of mapDouble.
The function "mapDouble" exists, but it is not used.

https://github.com/bytefish/PgBulkInsert/blob/2984394565fc5e3b460caca978b1b4f90c986e2b/PgBulkInsert/pgbulkinsert-jpa/src/main/java/de/bytefish/pgbulkinsert/jpa/JpaMapping.java#L222

Thanks.

**Comment by bytefish** [comment]
That's a bug. Feel free to create a Pull Request.

**Comment by bytefish** [comment]
Let's track this in Issue #58.
