### ISSUE TITLE
add #mapTime method to insert LocalTime similar to #mapDate

### ISSUE THREAD

**Issue by jonfreedman** [bytefish/PgBulkInsert#59]

**Comment by jonfreedman** [comment]
Looks like you beat me to it!

**Comment by bytefish** [comment]
Yours is better! Give me a moment to merge it. :-)

**Comment by bytefish** [comment]
I have to see, what we can do about the ``db.properties`` file, so it doesn't get overriden. I really don't want to introduce Docker or some kind of In-Memory DB.

**Comment by jonfreedman** [comment]
Using docker + TravisCI/CircleCI isn't a bad idea, it's just a bit of a fiddle to set up

**Comment by bytefish** [comment]
Indeed. I think I should have a look into the GitHub Pipelines some time. If you want... no obligations! ... I can turn this project into an organization, add you as a project collaborator and we might work on it? We can also remove my name from the Copyrights and so on, I am not this entitled. 👍

**Comment by jonfreedman** [comment]
I'll see if I have some time this week to take a look, GitHub pipelines works for me although I haven't used them before. Sounds like this is the way to go https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers  ---- On Mon, 11 May 2020 19:34:10 +0100  notifications@github.com  wrote ----

Indeed. I think I should have a look into the GitHub Pipelines some time. If you want... no obligations! ... I can turn this project into an organization, add you as a project collaborator and we might work on it? We can also remove my name from the Copyrights and so on, I am not this entitled. 👍

**Comment by bytefish** [comment]
Back to the original topic: I have released 5.1.0 with your changes. At the same time I have turned the Repository into an Organization and transferred Ownership of the Repository, so it is not tied to my moniker.

**Comment by jonfreedman** [comment]
I'm not seeing 5.1.0 in maven central yet: https://mvnrepository.com/artifact/de.bytefish.pgbulkinsert/pgbulkinsert-core

**Comment by bytefish** [comment]
According to the official Maven Search it is there:

* https://search.maven.org/artifact/de.bytefish.pgbulkinsert/pgbulkinsert-parent/5.1.0/pom
